version: 2.1

orbs:
  python: circleci/python@1.2.0

jobs:
  build:
    executor: python/default
    working_directory: /c/poc/fresh/tests
    steps:
      - checkout
      - run: python3 hello.py
  test:
    executor: python/default
    steps:
      - checkout
      - run: python3 test_hello.py

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
