# config.yml

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m unittest discover -s . -p "test_*.py"
      - store_artifacts:
          path: test-results.xml
          destination: test-results

  deploy:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: |
            docker build -t my_image .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker tag my_image $DOCKERHUB_USERNAME/my_image
