version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - run: pip install -r requirements.txt
      
  test:
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest
